--- !ruby/object:VR_ENV
browser: firefox
width: 1436
height: 838
panel_pos: 360
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- C:/RubyProjects/wordfindVR/Untitled
open_folders:
- C:/RubyProjects/wordfindVR
- C:/RubyProjects/wordfindVR/bin
current_file: C:/RubyProjects/wordfindVR/Untitled
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
